finish second and third section of portfolio
yasinabdmahmood/portfolio-website pull request #2
Opened 2022-07-02 18:38 UTC by yasinabdmahmood

# completing a second and third sections of the portfolio
 
[you can here to see the figma template that was chosen for this project .](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=1%3A1471)

2022-07-02 18:43 UTC, victorokoroji requested changes
Hi @yasinabdmahmood , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## ❌ Invalid Code Review Request

You have submitted a project, that has failed linter checks. Kindly fix the linter errors and submit again.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-07-02 21:14 UTC, 1GORDON requested changes
##
## Hi @yasinabdmahmood ✋

Good job so far!

## Highlights!
- Good feature branch name ✔️ 
- Good commit messages  ✔️ 
- Professional Readme ✔️
- Professional Pull request ✔️
- Linters are passing ✔️

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️

- [ ] You may please try to follow the Figma design as much as possible. Please remove the underline on your logo. And surround the hamburger icon in `<a>` tags since the icon is a clickable link.
- Your design
![underline](https://user-images.githubusercontent.com/63917725/177015081-0d4a58d8-8ad2-41c6-ad05-61ccc2fd8e11.PNG)


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@1GORDON` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-02 21:14 UTC, 1GORDON commented on index.html
> +        </h1>
Great job @yasinabdmahmood 🤝

- [ ] Just like in the Figma design, please try to align your `<h1>` accordingly.
- Your design
![your design](https://user-images.githubusercontent.com/63917725/177014918-f2e66604-33fc-4ce0-9191-75e65345960b.PNG)

- Figma design
![figma design](https://user-images.githubusercontent.com/63917725/177014925-20dc1e00-d58e-4496-bd09-a6ecb2f41771.PNG)

2022-07-02 21:14 UTC, 1GORDON commented on index.html
> +    </section>
Great job @yasinabdmahmood 🤝

- [ ] Please try to follow the Figma design as much as possible. You may please make your design identical.
- Your design
![your languages](https://user-images.githubusercontent.com/63917725/177015292-620fcb9b-47f0-4db2-aefd-242222d6aa35.PNG)

- Figma design
![figma languages](https://user-images.githubusercontent.com/63917725/177015308-8d9f803f-a55a-467a-b388-0ae4390fef0e.PNG)

2022-07-02 21:14 UTC, 1GORDON commented on index.html
> +    </section>
Great job @yasinabdmahmood 🤝

- [x] You may please try to follow the Figma design as much as you can. Please push the text to the left and align it properly. You may also reduce the size of the button.
- Your design
![your about](https://user-images.githubusercontent.com/63917725/177015402-f484db66-ffa4-47d9-b5b2-1e47a44d2cc4.PNG)

- Figma Design
![about](https://user-images.githubusercontent.com/63917725/177015430-85109c01-cbc1-4cdd-8a05-884b3851b6db.PNG)

2022-07-02 21:14 UTC, 1GORDON commented on index.html
> +                <a class="see-project2" href="">See Project</a>
Great work @yasinabdmahmood 🤝

- [x] You may try to make your buttons the same as in the Figma design. Please make the text color white
- Figma button
![Figma button](https://user-images.githubusercontent.com/63917725/177015620-deed85d7-7b50-4d42-a331-0155c2b86992.PNG)

- Your button
![Your button](https://user-images.githubusercontent.com/63917725/177015634-038473d0-33ed-4805-aee0-8b4adba87cd4.PNG)

2022-07-02 21:14 UTC, 1GORDON commented on index.html
> +                <a class="css-code" href="">Ruby</a>
Great job @yasinabdmahmood 🤝

- [x] As specified in the project requirements, please try to surround these language items in a `<ul>` and make each language an `<li>` tag.

2022-07-02 21:14 UTC, 1GORDON commented on styles.css
> +}
Great job @yasinabdmahmood 🤝

- [ ] You may please use the display grid instead of flex on this works section. This is how it is needed in the project requirements.

2022-07-03 00:19 UTC, vickymarz requested changes
Hi @yasinabdmahmood , 

Great work on making the changes requested by a previous reviewer 👏 🔥 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![](https://camo.githubusercontent.com/56bcd754643682fcc078b66eaa7278dead6c9c5013595c875b4ddcbe0f0ef0aa/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d2e676966)

## Top highlight 🎯

- The PR title and description are professional and descriptive ✅ 
- The commit messages are meaningful ✅ 
- Linters are working properly ✅ 


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-03 00:19 UTC, vickymarz commented on index.html
> +                    <li>Codepen</li>
- [ ] KIndly ensure that the bullet shapes are properly aligned with the text to match the Figma design👍.

| Figma Design  | Your Design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/63473584/177019758-2b8da50b-4497-44d8-954a-c603cecf224b.png) |![image](https://user-images.githubusercontent.com/63473584/177019772-02062e13-8771-42e0-a7e6-0d8bd88b3002.png)  |

2022-07-04 08:37 UTC, Ginohmk approved these changes
Hi Team, 

# STATUS: APPROVED 🟢

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## TO HIGHLIGHT: 
- Your project is professional 💯 
- Your repo is professional 💯 
- Well structured files 💯 
- You set up linter files and no errors. 💯 

![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-04 09:00 UTC, merged